cartesian_variable_impedance_controller:
    type: franka_human_friendly_controllers/CartesianVariableImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
joint_variable_impedance_controller:
    type: franka_human_friendly_controllers/JointVariableImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7