name = "OneDly Project"
license = "MIT"
licenselink = "https://github.com/cdeck3r/OneDly-Theme/blob/master/LICENSE.md"
description = "Theme for documenting One-Day-Only (OneDly) projects."
homepage = "https://github.com/cdeck3r/OneDly-Theme"
tags = ["documentation", "landing page", "opensource", "single page"]
features = ["github", "images" ]
min_version= "0.48"

[author]
     name = "Christian Decker"

# If porting an existing theme
[original]
    author =  "Omar Abdelhafith"
    homepage = "https://github.com/nsomar/github-project-landing-page"
    repo = "https://github.com/nsomar/github-project-landing-page"

